openapi: 3.1.0
info:
  title: Partner API - Postback Endpoint
  description: |
    API for handling postback notifications with various status types.
    This endpoint processes different types of user interactions and transactions.
    
    ## Status Types:
    
    **registration** - после регестрации на платформе.
    Get params:
    - subid={subid}
    - *status=reg
    - *datetime={datetime(UTC)}
    - ip={ip}
    - user_agent={user_agent}
    - *tid={unic_id_for_this_clients}
    
    **payview** - переход на страницу оплаты.
    Get params:
    - subid={subid}
    - *status=payview
    - *datetime={datetime(UTC)}
    - ip={ip}
    - user_agent={user_agent}
    - *tid={unic_id_for_this_clients}
    
    **sale** - после первой покупки (челенджа).
    Get params:
    - subid={subid}
    - *status=sale
    - *datetime={datetime(UTC)}
    - payment={value_in_float}
    - currency={USD, EUR, ...}
    - ip={ip}
    - user_agent={user_agent}
    - *tid={unic_id_for_this_clients}
    
    **rebill** - каждая последующая покупка (нового челенжа).
    Get params:
    - subid={subid}
    - *status=rebill
    - *datetime={datetime(UTC)}
    - payment={value_in_float}
    - currency={currency}
    - ip={ip}
    - user_agent={user_agent}
    - *tid={unic_id_for_this_clients}

  version: 1.0.4

servers:
  - url: http://example.com
    description: Production server

paths:
  /get-key/postback:
    get:
      summary: Unified postback notification endpoint
      description: |
        Handles various postback notifications for user interactions and transactions.
        Supports multiple status types with different parameter requirements.
      operationId: handlePostback
      tags:
        - Postback
      parameters:
        - name: subid
          in: query
          required: false
          description: Unique subscriber identifier
          schema:
            type: string
            example: "sub_12345"
        - name: status
          in: query
          required: true
          description: Status type indicating the type of postback
          schema:
            type: string
            enum:
              - reg
              - payview
              - sale
              - rebill
          examples:
            registration:
              summary: Registration completed
              description: User completed registration
              value: "reg"
            payview:
              summary: Payment view
              description: User navigated to payment page
              value: "payview"
            sale:
              summary: First purchase
              description: User completed first purchase
              value: "sale"
            rebill:
              summary: Subsequent purchase
              description: User completed subsequent purchase
              value: "rebill"
        - name: datetime
          in: query
          required: true
          description: Timestamp in UTC format
          schema:
            type: string
            format: date-time
            example: "2024-01-15T10:30:00Z"
        - name: payment
          in: query
          required: false
          description: Payment amount as float value (required for sale and rebill statuses)
          schema:
            type: number
            format: float
            example: 99.99
        - name: currency
          in: query
          required: false
          description: Payment currency code (required for sale and rebill statuses)
          schema:
            type: string
            enum: [USD, EUR, GBP, CAD, AUD]
            example: "USD"
        - name: tid
          in: query
          required: true
          description: Unique transaction ID for this client (available for any status)
          schema:
            type: string
            example: "txn_67890"
        - name: promo_code
          in: query
          required: false
          description: Promo code used for the transaction (available for any status)
          schema:
            type: string
            example: "SUMMER2024"
        - name: ip
          in: query
          required: false
          description: Client IP address
          schema:
            type: string
            example: "203.0.113.45"
        - name: user_agent
          in: query
          required: false
          description: Client user agent string
          schema:
            type: string
            example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
      responses:
        '200':
          description: Postback processed successfully
          content:
            text/plain:
              schema:
                type: string
                example: "Success"
              examples:
                success_response:
                  summary: Success response
                  description: Simple success message
                  value: "Success"
        '400':
          description: Bad request - missing required parameters
          content:
            text/plain:
              schema:
                type: string
                example: "400"
        '422':
          description: Unprocessable entity - invalid parameter values
          content:
            text/plain:
              schema:
                type: string
                example: "422"
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: "500"

  /get-key/promo:
    get:
      summary: Validate promo code
      description: Validates provided promo code and returns validation status.
      operationId: validatePromoCode
      parameters:
        - name: promo_code
          in: query
          required: true
          description: Promo code to validate
          schema:
            type: string
            example: "SUMMER2024"
      responses:
        '200':
          description: Promo code validation result
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    type: boolean
                    description: Whether the promo code is valid

tags:
  - name: Postback
    description: Postback notification endpoints for tracking user interactions and transactions
